kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      name: rest
    - port: 9200
      name: inter-node
  selector:
    app: elasticsearch
  clusterIP: None